# Generated by Django 3.2.5 on 2021-10-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders_name', models.CharField(max_length=50)),
                ('receivers_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
